config/routes.rb
Newtube::Application.routes.draw do
  
  root to: 'users#show'

  match 'user/edit' => 'users#edit', as: :edit_current_user

  match 'signup' => 'users#new', as: :signup

  match 'logout' => 'sessions#destroy', as: :logout

  match 'login' => 'sessions#new', as: :login

  resources :sessions

  resources :users do
    collection do
      get 'search_show'
    end
  end

  match 'user/add_show' => 'users#add_show', as: :add_show

  match 'user/remove_show' => 'users#remove_show', as: :remove_show

  match 'user/set_show_status' => 'users#set_show_status', as: :set_show_status, via: :post

  match 'user/update_show' => 'users#update_show', as: :update_show
  

end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  
  has_many :user_follows
  has_many :shows, through: :user_follows

  has_many :user_watches
  has_many :episodes, through: :user_watches
  
  # new columns need to be added here to be writable through mass assignment
  attr_accessible :username, :email, :password, :password_confirmation

  attr_accessor :password
  before_save :prepare_password

  validates_presence_of :username
  validates_uniqueness_of :username, :email, :allow_blank => true
  validates_format_of :username, :with => /^[-\w\._@]+$/i, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :minimum => 4, :allow_blank => true

  # login can be either username or email address
  def self.authenticate(login, pass)
    user = find_by_username(login) || find_by_email(login)
    return user if user && user.password_hash == user.encrypt_password(pass)
  end

  def encrypt_password(pass)
    BCrypt::Engine.hash_secret(pass, password_salt)
  end

  private

  def prepare_password
    unless password.blank?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = encrypt_password(password)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ERB::Util
  include TVDB
  before_filter :login_required, :except => [:new, :create]

  def show

    # What shows does this user follow?
    follow_shows = current_user.shows.order(:name)

    # Go through each follow, storing the show name
    @data = Array.new
    follow_shows.each do |fs|

      # Get all of the episode info
      episodes = Array.new
      Episode.joins('left join user_watches on id = user_watches.episode_id').order(:first_aired, :season, :number).where(show_id: fs.id).each do |e|
        episode = Hash.new
        episode[:id]          = e.id
        episode[:season]      = e.season
        episode[:number]      = e.number
        episode[:name]        = e.name
        episode[:watched]     = e.user_watches.where(user_id: current_user)
        episode[:first_aired] = e.first_aired
        episodes << episode if params[:show_all].present? || episode[:watched].blank?
      end

      show_data = Hash.new
      show_data[:id]       = fs.id
      show_data[:name]     = fs.name
      show_data[:episodes] = episodes

      # Add to our dataset
      @data << show_data

    end

  end

  # We need to know the show id so that we can search to see if this episode already exists
  def add_episodes(tvdb, show_id)

    # Add episodes to the show
    episodes = Array.new

    # Go through all episodes returned to us
    Array.wrap(tvdb['Data']['Episode']).each do |e|

      # Find or create, and then update
      episode = Episode.find_or_create_by_show_id_and_season_and_number(show_id, e['SeasonNumber'], e['EpisodeNumber'])
      
      # Update the info
      episode.name        = e['EpisodeName']
      episode.tvdbid      = e['id']
      episode.first_aired = e['FirstAired']
      episode.save
      
      # Put it into our episodes group
      episodes << episode

    end

    return episodes
  end

  # Must have a valid show id -- we already have the show in our database, we just want to find new episodes

  def update_show
    show = Show.find_by_id(params[:update])
    redirect_to users_path, alert: 'Unable to update show' unless show

    # Try to do a pull from thetvdb.com
    tvdb = tvdb_query_series_all(show.tvdbid)
    show.episodes = add_episodes(tvdb, show.id)

    redirect_to users_path, notice: 'Show successfully updated'
  end

  def set_show_status
    if params[:status] == '1'
      params[:watched_ids].each do |wid|
        UserWatch.find_or_create_by_user_id_and_episode_id(user_id: current_user.id, episode_id: wid)
      end
    else
      UserWatch.where(user_id: current_user.id, episode_id: params[:watched_ids]).delete_all
    end
    redirect_to users_path
  end

  def search_show
    @tvdb = tvdb_search_series(URI.escape(params[:search] || ''))
  end

  def add_show

    # Can only create if we're passed an ID...
    if params[:add].blank?
      redirect_to users_path, alert: 'Must provide a show ID' 
      return
    end

    # Do we already have it?
    if UserFollow.joins(:show).where(user_id: current_user, shows: { tvdbid: params[:add] }).present?
      redirect_to user_path(current_user), alert: 'Show already followed' 
      return
    end

    # Try to find the show in the database
    show = Show.find_by_tvdbid(params[:add])

    # If it's not in the database...
    unless show
      # Have to retrieve the info for the show and save it to the database
      
      # Try to do a pull from thetvdb.com
      tvdb = tvdb_query_series_all(params[:add])

      # First off, add the show itself
      show = Show.create({name: tvdb['Data']['Series']['SeriesName'], tvdbid: tvdb['Data']['Series']['id']})
      
      # Then add the episodes
      show.episodes = add_episodes(tvdb, show.id)

    end

    # Add it to our user's follows
    current_user.user_follows.create(show_id: show.id)

    # If it does exist, we'll make a call out for the data on it
    redirect_to user_path(current_user), notice: 'Show successfully added'

  end

  def remove_show
    # Get the show we're trying to remove
    show = Show.find_by_id(params[:remove])
    # Remove any episode watches for this show
    UserWatch.where(user_id: current_user.id, episode_id: show.episodes).delete_all
    # Remove the show follow itself
    UserFollow.where(user_id: current_user.id, show_id: show.id).delete_all
    redirect_to users_path, notice: 'Show successfully removed'
  end

  # This is our root, so if we're logged in, we'll redirect to #show
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, :notice => "Thank you for signing up! You are now logged in."
    else
      render :action => 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to root_url, :notice => "Your profile has been updated."
    else
      render :action => 'edit'
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
  include TVDB
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email, "Email Address" %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p><%= f.submit (@user.new_record? ? "Sign up" : "Update") %></p>
<% end %>

app/views/users/_menu.html.erb
<div>
  Hello <%= link_to current_user.username, user_path(current_user) %>!
  <%= link_to 'Search', search_show_users_path %>
  <%= link_to 'Show All', users_path(show_all: '1') %>
  <%= link_to 'Show Unwatched', users_path %>
  <%= link_to 'Log out', logout_path(current_user) %>
</div>

app/views/users/edit.html.erb
<% title "Update Profile" %>

<%= render 'form' %>

app/views/users/index.html.erb
<div>
  Hello <%= current_user.username %>!
  <%= link_to 'Log out', logout_path(current_user) %>
  <%= link_to 'Show All', users_path(show_all: '1') %>
  <%= link_to 'Show Unwatched', users_path %>
</div>

<%# Search for a series %>
<%= form_tag search_show_users_path do %>
  <%= label_tag(:search, 'Search Series') %>
  <%= text_field_tag(:search) %>
  <%= submit_tag('Search') %>
<% end %>

<%# Show a form for adding a new series %>
<%#= form_tag add_show_path do %>
  <%#= label_tag(:add, 'Add Series') %>
  <%#= text_field_tag(:add) %>
  <%#= submit_tag('Add') %>
<%# end %>

<%# Display the follows for this user %>
<% @data.each do |d| %>
  <%= content_tag :h1, d[:name] %>
  <%= link_to 'Remove Series', remove_show_path(remove: d[:id]) %>
  <%= link_to 'Update Series', update_show_path(update: d[:id]) %>

  <%# Show the episodes in a table %>
  <%= form_tag set_show_status_path do %>
    <table>
      <thead>
        <tr>
          <th><%= check_box_tag nil, nil, false, class: 'select_all' %></th>
          <th>Season</th>
          <th>Episode</th>
          <th>Name</th>
          <th>First Aired</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <% d[:episodes].each do |e| %>
          <tr>
            <td><%= check_box_tag 'watched_ids[]', e[:id] %></td>
            <%= content_tag :td, e[:season] %>
            <%= content_tag :td, e[:number] %>
            <%= content_tag :td, e[:name]   %>
            <%= content_tag :td, e[:first_aired] %>
            <%= content_tag :td, e[:watched].blank? ? 'Unwatched' : 'Watched' %>
          </tr>
        <% end %>
      </tbody>
    </table>
    Mark as <%= select_tag 'status', options_for_select([['Watched','1'],['Unwatched','0']]) %>
    <%= submit_tag 'Save Status' %>
  <% end %>

<% end %>

app/views/users/new.html.erb
<% title "Sign up" %>

<p>Already have an account? <%= link_to "Log in", login_path %>.</p>

<%= render 'form' %>

app/views/users/search_show.html.erb
<%#= debug @tvdb %>

<%= render 'menu' %>

<%# Search for a series %>
<%= form_tag search_show_users_path, method: :get do %>
  <%= label_tag(:search, 'Search Series') %>
  <%= text_field_tag(:search) %>
  <%= submit_tag('Search') %>
<% end %>

<%#= debug @tvdb %>

<% if @tvdb['Data'].present? %>
  <table>

    <% Array.wrap(@tvdb['Data']['Series']).each do |s| %>
      <tr>
        <td>
          <%= s['SeriesName'] %>
        </td>
        <td>
          <%= button_to 'Add', add_show_path(add: s['seriesid']) %>
        </td>
      </tr>
      <%#= image_tag get_banner_uri(s['banner']) %>
    <% end %>

  </table>
<% end %>

app/views/users/show.html.erb
<%= render 'menu' %>

<%# Show a form for adding a new series %>
<%#= form_tag add_show_path do %>
  <%#= label_tag(:add, 'Add Series') %>
  <%#= text_field_tag(:add) %>
  <%#= submit_tag('Add') %>
<%# end %>

<%# Display the follows for this user %>
<% @data.each do |d| %>
  <%= content_tag :h1, d[:name] %>
  <%= link_to 'Remove Series', remove_show_path(remove: d[:id]) %>
  <%= link_to 'Update Series', update_show_path(update: d[:id]) %>

  <%# Show the episodes in a table %>
  <%= form_tag set_show_status_path do %>
    <table>
      <thead>
        <tr>
          <th><%= check_box_tag nil, nil, false, class: 'select_all' %></th>
          <th>Season</th>
          <th>Episode</th>
          <th>Name</th>
          <th>First Aired</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <% d[:episodes].each do |e| %>
          <tr>
            <td><%= check_box_tag 'watched_ids[]', e[:id] %></td>
            <%= content_tag :td, e[:season] %>
            <%= content_tag :td, e[:number] %>
            <%= content_tag :td, e[:name]   %>
            <%= content_tag :td, e[:first_aired] %>
            <%= content_tag :td, e[:watched].blank? ? 'Unwatched' : 'Watched' %>
          </tr>
        <% end %>
      </tbody>
    </table>
    Mark as <%= select_tag 'status', options_for_select([['Watched','1'],['Unwatched','0']]) %>
    <%= submit_tag 'Save Status' %>
  <% end %>

<% end %>